project_id = "fidjmnjluqppsggovopi"

[functions.snowflake-query]
verify_jwt = false

[functions.azure-sso]
verify_jwt = false

[functions.send-manager-email]
verify_jwt = false

[functions.check-document-expiry]
verify_jwt = false
